### ISSUE TITLE
Sentry-raven is deprecated

### ISSUE THREAD

**Issue by Vin0uz** [loopstudio/rails-graphql-api-boilerplate#305]
Hi guys,

Thank you for the cool boilerplate, and the clear doc ! 🙏

In the Gemfile, you use `sentry-raven` but I think this is now deprecated, and should use `sentry-ruby` (and maybe `sentry-rails)

The [Migration Guide is here](https://docs.sentry.io/platforms/ruby/migration/), I can propose a diff if you want btw :) 

Thanks again for the time saved though 😅

**Comment by mconiglio** [comment]
hello @Vin0uz, we are glad you like it! if you have any feedback or ideas for improvement feel free to ping us!

thanks for the heads up about sentry! we will look into it as soon as possible 👍
